apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: digicon
spec:
  replicas: 10
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.4
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql.digicon.svc.cluster.local
            - name: WORDPRESS_DB_USER
              value: root
            - name: WORDPRESS_DB_PASSWORD
              value: rootpass
            - name: WORDPRESS_DB_NAME
              value: appdb
          ports:
            - containerPort: 80
